---
- name: "Init app"
  ansible.builtin.command:
    cmd: "{{ stalwart_executable_path }} --init {{ stalwart_install_path }}"
    creates: "{{ stalwart_config_file_path }}"
  become: true
  become_user: "{{ stalwart_system_user }}"

- name: "Setup configuration"
  ansible.builtin.template:
    src: "opt/stalwart/etc/config.toml.j2"
    dest: "{{ stalwart_config_file_path }}"
    owner: "{{ stalwart_system_user }}"
    group: "{{ stalwart_system_group }}"
    mode: "0640"
  notify: "Restart Stalwart"

- name: "Ensure service is in correct state"
  ansible.builtin.service:
    name: "{{ stalwart_service_name }}"
    state: "{{ stalwart_service_state }}"
    enabled: "{{ stalwart_service_enabled }}"
  when: not ansible_check_mode
