---
- name: "Create Stalwart group"
  ansible.builtin.group:
    name: "{{ stalwart_system_group }}"
    system: true

- name: "Create Stalwart user"
  ansible.builtin.user:
    name: "{{ stalwart_system_user }}"
    group: "{{ stalwart_system_group }}"
    create_home: false
    home: "{{ stalwart_install_path }}"
    shell: "/usr/sbin/nologin"
    system: true

- name: "Check if server is already installed"
  ansible.builtin.stat:
    path: "{{ stalwart_executable_path }}"
  register: "stalwart_exec"

- name: "Get server version if stalwart is installed"
  when: stalwart_exec.stat.exists
  block:
    - name: "Get server version"
      ansible.builtin.command: "{{ stalwart_executable_path }} -V"
      failed_when: false
      changed_when: false
      check_mode: false
      register: "stalwart_output"

    - name: "Set current installed server version"
      ansible.builtin.set_fact:
        stalwart_current_version: "{{ stalwart_output.stdout_lines[0] }}"

- name: "Check if CLI is already installed"
  ansible.builtin.stat:
    path: "{{ stalwart_cli_executable_path }}"
  register: "stalwart_cli_exec"

- name: "Get CLI version if stalwart-cli is installed"
  when: stalwart_cli_exec.stat.exists
  block:
    - name: "Get CLI version"
      ansible.builtin.command: "{{ stalwart_cli_executable_path }} --version"
      failed_when: false
      changed_when: false
      check_mode: false
      register: "stalwart_cli_output"

    - name: "Set current installed CLI version"
      ansible.builtin.set_fact:
        stalwart_cli_current_version: "{{ stalwart_cli_output.stdout_lines[0] | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)') }}"
