---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    stalwart_server_hostname: "mail.example.com"
    stalwart_default_domain: "example.com"
    stalwart_system_user: "stalwartu"
    stalwart_system_group: "stalwartg"
    stalwart_server_listeners:
      - name: "smtp"
        bind: "[::]:25"
        protocol: "smtp"
      - name: "submission"
        bind: "[::]:587"
        protocol: "smtp"
      - name: "submissions"
        bind: "[::]:465"
        protocol: "smtp"
        options:
          tlsImplicit: true
      - name: "imaptls"
        bind: "[::]:993"
        protocol: "imap"
        options:
          tlsImplicit: true
      - name: "pop3s"
        bind: "[::]:995"
        protocol: "pop3"
        options:
          tlsImplicit: true
      - name: "https"
        protocol: "http"
        bind: "[::]:443"
        options:
          tlsImplicit: true
      - name: "http"
        protocol: "http"
        bind: "[::]:8080"

    stalwart_additional_configs:
      - "@type": "upsert"
        object: "AllowedIp"
        matchOn: ["address"]
        value:
          allow-1:
            address: "10.0.0.0/8"

  tasks:
    - name: "Import role"
      ansible.builtin.import_role:
        name: "plopoyop.stalwart"
