---
name: test role
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distro:
          - debian13
          - debian12
          - rockylinux9
          - rockylinux10
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Prepare env
        run: devenv shell task prepare
      - name: Run molecule test
        run: devenv shell task test
